using StabilizatorHub.Application.Common;
using StabilizatorHub.Application.Dtos;

namespace StabilizatorHub.Application.Services;

/// <summary>
/// Device ownership and household membership use cases.
///
/// Two kinds of codes open access to a device:
///  - the PAIRING code shown on the device OLED while unclaimed - proves
///    physical possession; the redeemer becomes the Owner;
///  - an INVITE code generated by the Owner inside the app - lets the rest of
///    the household join the same device as Members with their own accounts.
/// </summary>
public interface IDeviceClaimService
{
    /// <summary>
    /// Redeems either kind of code: a matching pairing code claims the device
    /// (Owner), a matching invite code joins it (Member).
    /// </summary>
    /// <param name="rateLimitKey">Caller identity for brute-force limiting (user id or client IP).</param>
    Task<OperationResult<DeviceDto>> RedeemCodeAsync(
        string userId, string? userEmail, string code, string rateLimitKey,
        string? ipAddress, CancellationToken ct = default);

    /// <summary>Creates a time-limited, multi-use invite code (owner only). The code is returned once.</summary>
    Task<OperationResult<DeviceInviteDto>> CreateInviteAsync(
        string userId, string? userEmail, string deviceId, string? ipAddress, CancellationToken ct = default);

    /// <summary>Lists the members of a device (owner only).</summary>
    Task<OperationResult<IReadOnlyList<DeviceMemberDto>>> GetMembersAsync(
        string userId, string deviceId, CancellationToken ct = default);

    /// <summary>
    /// Removes a member: the owner can remove anyone but themselves; a member
    /// can remove only themselves (leave). The owner exits via Release.
    /// </summary>
    Task<OperationResult> RemoveMemberAsync(
        string callerUserId, string? callerEmail, string deviceId, string targetUserId,
        string? ipAddress, CancellationToken ct = default);

    /// <summary>
    /// Detaches the device from ALL accounts (owner only); the firmware then
    /// generates a fresh pairing code, so it can be sold/re-claimed safely.
    /// </summary>
    Task<OperationResult> ReleaseAsync(
        string userId, string? userEmail, string deviceId, string? ipAddress, CancellationToken ct = default);

    Task<OperationResult<DeviceDto>> RenameAsync(
        string userId, string deviceId, string newName, CancellationToken ct = default);
}
